{{- $release := .Values.release }}
{{- $source := .Values.source }}
{{- $name := .Values.name }}
{{- $destination := .Values.destination_namespace }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- if or (eq $release "ci-cd") (eq $release "cluster-ops") (eq $release "pm") }}
  name: {{ $name }}
{{- else }}
  name: {{ $release }}-{{ $name }}
{{- end }}
  labels:
    destination-namespace: {{ $destination }}
{{- if .Values.values }}
{{- if .Values.values.fullnameOverride }}
{{- if contains .Values.values.fullnameOverride $name }}
    app.kubernetes.io/instance: {{ .Values.values.fullnameOverride }}
{{- end }}
{{- else }}
    app.kubernetes.io/instance: {{ $name }}
{{- end }}
{{- end }}
spec:
  destination:
    namespace: {{ $destination }}
    server: {{ .Values.cluster_api | default "https://kubernetes.default.svc" }}
  project: {{ .Values.project | default "default" }}
  source:
{{- if or .Values.helm_values .Values.values }}
    helm:
{{- if .Values.helm_values }}
      valueFiles:
{{- toYaml .Values.helm_values | nindent 8 }}
{{- end }}
{{- if (.Values.values) }}
      values: |
{{- toYaml .values | nindent 8 }}
{{- end }}
{{- if or .Values.releaseName $name }}
      releaseName: {{ .Values.releaseName | default $name }}
{{- end }}
{{- end }}
    {{- if .Values.source_path }}
    path: {{ .Values.source_path | default "." }}
    {{- end }}
    repoURL: {{ $source }}
    targetRevision: {{ .Values.source_ref | default "main" | quote }}
    {{- if not .Values.source_path }}
    chart: {{ .Values.chart_name | default $name }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/containers/1/image
    - group: integreatly.org
      kind: GrafanaDataSource
      jsonPointers:
        - /spec/datasources/0/secureJsonData/httpHeaderValue1
